### ISSUE TITLE
SELECT * query fails

### ISSUE THREAD

**Issue by berezovskyi** [Institute-Web-Science-and-Technologies/koral#3]
```
SELECT * WHERE {
        ?s ?p ?o .
}
```

results in 

```
QueryParseException: Encountered " "in" "in "" at line 1, column 1.
Was expecting one of:
    "\ufeff" ...
    "base" ...
    "prefix" ...
    "select" ...
    "describe" ...
    "construct" ...
    "ask" ...

	at org.apache.jena.sparql.lang.ParserSPARQL11.perform(ParserSPARQL11.java:100)
```

**Comment by berezovskyi** [comment]
```
select ?s ?p ?o where {
     ?s ?p ?o .
 }
```

fails as well

**Comment by ghost** [comment]
Could you please provide the steps you have performed so that I can reproduce the error.

I tested both queries by reading them from a file or by entering them into the console directly. In both cases they worked without error.

**Comment by berezovskyi** [comment]
From my terminal history, I just ran

`java -jar target/koral.jar client -m 127.0.0.1 query -t BUSHY -o out.csv in.sparql`

where I assume `in.sparql` contained one of the given queries.

**Comment by ghost** [comment]
The command
`java -jar target/koral.jar client -m 127.0.0.1 query -t BUSHY -o out.csv in.sparql`
assumes in.sparql would be the query. To execute a query in a file the command would be
`java -jar target/koral.jar client -m 127.0.0.1 query -t BUSHY -o out.csv -q in.sparql`

**Comment by berezovskyi** [comment]
Nice, thank you!
